### ISSUE TITLE
Are Ghost Editor exports compatible with Behavior3js loading and processing?

### ISSUE THREAD

**Issue by tebb** [renatopp/ghost-editor#3]
Hello Renato P P.

Great work here and the BT explanations were very helpful too. Thanks. Interesting topic too.

It looks like Ghost Editor is a much expanded version of Behaviour3 Editor (http://editor.behavior3.com/) with extra modulators, inputs etc.

My queries are:  

Can I load and traverse trees *created in Ghost* using the Behavior3js client library?
 (https://github.com/behavior3/behavior3js)

Or am I misunderstanding?

**Comment by renatopp** [comment]
Hey @tebb , thank you for the feedback.

Ghost editor is a specific version for Hanson robotics, they have their own implementation of BTs, thus it is not compatible with b3js client. 

It has been some time since I made the last changes on the b3 project, so I recommend that you take a look on the forked version. There is a big pull request to the editor at

https://github.com/behavior3/behavior3editor/pull/28

It may have some good improvements on it.
